#!/bin/bash
# Transfers a file from local client to a server using scp with SSH key

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables for clarity
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Transfer the file to the user's home directory (~/)
# Disable strict host key checking with the -o option
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Exit with the status of the scp command
exit $?
